steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_REPOSITORY}:$_TAG', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_REPOSITORY}:$_TAG']

  # Deploy to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_REPOSITORY}:$_TAG'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

# Define substitutions
substitutions:
  _TAG: 'latest' # Or use $SHORT_SHA for the short SHA hash of the commit
  _IMAGE_REPOSITORY: 'danflask'
  _SERVICE_NAME: 'danslab'
  _REGION: 'europe-west2' # London region

# Define options such as timeout
timeout: '1200s' # 20 minutes
